### ISSUE TITLE
Adicionar documentação do SQL Server

### ISSUE THREAD

**Issue by eduardoklosowski** [rdornel/material#4]
Falta links para a documentação do Microsoft SQL Server em [Extra > Documentação dos SGBD](https://materialdornel.readthedocs.io/pt_BR/latest/extra/documentacao.html)

**Comment by rdornel** [comment]
Seguem os links para a documentação do SQL Server 2016
https://msdn.microsoft.com/pt-br/library/ms130214.aspx
Aqui a documentação de comandos e desenvolvimento
https://technet.microsoft.com/pt-br/library/bb500155(v=sql.105).aspx
